import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AudioPreloader} from '../lib/audio-preloader.ts';
import {validPreview,rememberPreview,previewUrl} from '../lib/preview-urls.ts';
test('preload and play share a single download and decoded result',async()=>{let fetches=0,decodes=0;const loader=new AudioPreloader(async()=>{decodes++;return {duration:30}},async()=>{fetches++;return new Response(new Uint8Array([1,2]))});const preload=loader.load(1);assert.equal(loader.load(1),preload);const audio=await preload;assert.equal(await loader.load(1),audio);assert.equal(fetches,1);assert.equal(decodes,1);loader.clear()});
test('next track stays warm while previous track is released',async()=>{let fetches=0;const loader=new AudioPreloader(async()=>({duration:30}),async()=>{fetches++;return new Response('audio')});await loader.load(1);const next=await loader.load(2);loader.retain([2,3]);assert.equal(await loader.load(2),next);assert.equal(fetches,2);await loader.load(1);assert.equal(fetches,3);loader.clear()});
test('failed preload can be retried on play',async()=>{let calls=0;const loader=new AudioPreloader(async()=>({duration:30}),async()=>new Response('audio',{status:++calls===1?503:200}));await assert.rejects(loader.load(1));assert.equal((await loader.load(1)).duration,30);assert.equal(calls,2);loader.clear()});
test('filter changes cancel obsolete downloads',async()=>{let signal;const loader=new AudioPreloader(async()=>({}),async(_url,options)=>{signal=options.signal;return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}))});const pending=loader.load(1);loader.retain([2]);assert(signal.aborted);await assert.rejects(pending);loader.clear()});
test('preview metadata is restricted to the music CDN',()=>{assert(!validPreview('https://example.com/audio.mp3'));assert(!validPreview('https://cdn.dzcdn.net.evil.test/audio'));assert(!validPreview('http://cdn.dzcdn.net/audio'));assert(validPreview('https://cdn-preview.dzcdn.net/audio'));rememberPreview(123,'https://cdn-preview.dzcdn.net/audio');assert.equal(previewUrl('123'),'https://cdn-preview.dzcdn.net/audio')});

test('browser fetch keeps its global receiver during preload',async()=>{const original=globalThis.fetch;let requests=0;try{globalThis.fetch=async function(){assert.equal(this,globalThis,'fetch must be invoked on its browser global');requests++;return new Response('audio')};const loader=new AudioPreloader(async()=>({duration:30}));assert.equal((await loader.load(77)).duration,30);assert.equal(requests,1);loader.clear()}finally{globalThis.fetch=original}});
