import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';
function modules(overrides={}){const cache={};return function load(file){file=path.resolve(file);if(cache[file])return cache[file];const exports={};cache[file]=exports;const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',code)(id=>overrides[id]||load(path.resolve(path.dirname(file),id+'.ts')),exports);return exports}}
test('exactly the seven requested menu choices, with rotating artists',()=>{const {GENRES,artistPage}=modules()('lib/genre-seeds.ts');assert.deepEqual(GENRES.map(g=>g.id),['all','pop','hiphop','rock','rnb','country','kpop']);const a=artistPage('pop',0),b=artistPage('pop',1);assert.equal(a.artists.length,8);assert(a.artists.every(n=>!b.artists.includes(n)));assert.equal(artistPage('all',0).pages,18)});
test('catalog rejects fuzzy artist hits and deduplicates releases',async()=>{let names=new Map(),next=1;const api=async p=>{if(p.startsWith('/search/artist')){const name=new URL('https://x'+p).searchParams.get('q');const id=next++;names.set(id,name);return {data:[{id:999,name:'Wrong Artist'},{id:998,name,nb_fan:1},{id,name,nb_fan:1000000}]}}if(p.startsWith('/artist/')){const id=Number(p.split('/')[2]);if(!p.includes('/top'))return {id,nb_fan:1000000};return {data:[{id:id*10,title:'Song',title_short:'Song',artist:{id,name:names.get(id)},rank:10000+id,preview:'https://cdn.dzcdn.net/a',album:{id:1,cover_big:'https://cdn.example/cover.jpg'}},{id:id*10+1,title:'Song (Remastered)',title_short:'Song',artist:{id,name:names.get(id)},rank:20000+id,preview:'https://cdn.dzcdn.net/a',album:{id:1,cover_big:'https://cdn.example/cover.jpg'}},{id:id*10+2,title:'Wrong song',artist:{id:999,name:'Wrong'},rank:900000,preview:'https://cdn.dzcdn.net/a',album:{id:1,cover_big:'https://cdn.example/cover.jpg'}}]}}};const {catalog}=modules({'./deezer':{deezer:api}})('lib/music-catalog.ts');const result=await catalog('pop','any',0);assert.equal(result.tracks.length,8);assert(result.tracks.every(t=>t.title!=='Wrong song'));assert.equal(new Set(result.tracks.map(t=>t.key)).size,8);assert.equal(result.stats.resolvedArtists,8);assert(result.tracks.every(t=>t.cover==='https://cdn.example/cover.jpg'),'cover must reach the client payload');assert.equal(result.pages,3)});
test('difficulty bands preserve popularity order',()=>{const {difficultyPool}=modules()('lib/catalog.ts');const songs=Array.from({length:100},(_,rank)=>({rank}));const easy=difficultyPool(songs,'easy'),impossible=difficultyPool(songs,'impossible');assert.equal(easy.length,20);assert.equal(impossible.length,20);assert(Math.min(...easy.map(s=>s.rank))>Math.max(...impossible.map(s=>s.rank)))});

test('easy queue includes every eligible artist despite different popularity scales',()=>{const {balancedDifficultyPool}=modules()('lib/catalog.ts');const songs=Array.from({length:8},(_,artist)=>Array.from({length:30},(_,i)=>({artist:'Artist '+artist,rank:(artist+1)*100000+i,id:artist*100+i}))).flat();const easy=balancedDifficultyPool(songs,'easy',()=>0.4);assert.equal(new Set(easy.slice(0,8).map(t=>t.artist)).size,8);assert(easy.every(t=>t.id%100>=24));assert.equal(new Set(easy.map(t=>t.id)).size,easy.length);const hard=balancedDifficultyPool(songs,'impossible',()=>0.4);assert(hard.every(t=>t.id%100<8));});

test('artists with tied ranks are not discarded',()=>{const {balancedDifficultyPool}=modules()('lib/catalog.ts');const songs=Array.from({length:8},(_,artist)=>Array.from({length:30},(_,i)=>({artist:'Artist '+artist,rank:0,id:artist*100+i}))).flat();const easy=balancedDifficultyPool(songs,'easy',()=>0.4);assert.equal(new Set(easy.slice(0,8).map(t=>t.artist)).size,8);assert(easy.every(t=>t.id%100<8));});

test('artist popularity decreases across all five levels',()=>{const {artistTier,songTier}=modules()('lib/popularity.ts');const artists=Array.from({length:100},(_,i)=>({id:i,name:'Artist '+i,fans:i*10000}));const levels=['easy','medium','hard','expert','impossible'];const tiers=levels.map(l=>artistTier(artists,l));for(let i=0;i<4;i++)assert(Math.min(...tiers[i].map(a=>a.fans))>Math.max(...tiers[i+1].map(a=>a.fans)));assert.equal(new Set(tiers.flat().map(a=>a.id)).size,100);const songs=Array.from({length:100},(_,rank)=>({rank}));assert.deepEqual(songTier(songs,'easy').map(s=>s.rank),[99,98,97,96,95]);assert(songTier(songs,'impossible').every(s=>s.rank<25));});

test('song tiers never overlap and keep the popularity order at any list size',()=>{const {songTier}=modules()('lib/popularity.ts');const levels=['easy','medium','hard','expert','impossible'];for(let length=1;length<=40;length++){const songs=Array.from({length},(_,rank)=>({rank}));const picked=levels.map(level=>songTier(songs,level).map(s=>s.rank));const all=picked.flat();assert.equal(new Set(all).size,all.length,'overlapping tiers at length '+length);assert(picked[0].length>0,'easy tier is empty at length '+length);for(let i=0;i<4;i++)if(picked[i].length&&picked[i+1].length)assert(Math.min(...picked[i])>Math.max(...picked[i+1]),levels[i]+' is not above '+levels[i+1]+' at length '+length)}});

test('shared popularity scale separates the levels while every artist keeps a slot',()=>{const {balancedDifficultyPool}=modules()('lib/catalog.ts');const songs=Array.from({length:8},(_,artist)=>Array.from({length:40},(_,i)=>({artist:'Artist '+artist,rank:i*8+artist,id:artist*100+i}))).flat();const levels=['easy','medium','hard','expert','impossible'];const pools=levels.map(level=>balancedDifficultyPool(songs,level,()=>0.4));for(let i=0;i<5;i++){assert(pools[i].length>0,levels[i]+' pool is empty');assert.equal(new Set(pools[i].slice(0,8).map(t=>t.artist)).size,8,levels[i]+' lost an artist');assert.equal(new Set(pools[i].map(t=>t.id)).size,pools[i].length,levels[i]+' repeats a track')}for(let i=0;i<4;i++)assert(Math.min(...pools[i].map(t=>t.rank))>Math.max(...pools[i+1].map(t=>t.rank)),levels[i]+' and '+levels[i+1]+' mix')});

test('era filtering keeps the whole catalog instead of a truncated album budget',async()=>{let albumLookups=0,artistListings=0,searches=0;let next=1;const names=new Map();const api=async p=>{if(p.startsWith('/search/artist')){searches++;const name=new URL('https://x'+p).searchParams.get('q');const id=next++;names.set(id,name);return {data:[{id,name,nb_fan:1000000}]}}const albums=p.match(/^\/artist\/(\d+)\/albums/);if(albums){artistListings++;const id=Number(albums[1]);const data=Array.from({length:30},(_,i)=>({id:id*1000+i,release_date:'2015-04-01'}));return {data,total:data.length}}if(p.startsWith('/album/')){albumLookups++;return {release_date:'2015-04-01'}}const artist=p.match(/^\/artist\/(\d+)/);const id=Number(artist[1]);if(!p.includes('/top'))return {id,nb_fan:1000000};return {data:Array.from({length:30},(_,i)=>({id:id*1000+i,title:'Song '+i,title_short:'Song '+i,rank:100000-i,preview:'https://cdn.dzcdn.net/preview',link:'',artist:{id,name:names.get(id)},album:{id:id*1000+i}}))}};const {catalog}=modules({'./deezer':{deezer:api}})('lib/music-catalog.ts');const {balancedDifficultyPool}=modules()('lib/catalog.ts');const result=await catalog('pop','2010',0);assert.equal(artistListings,8);assert.equal(albumLookups,0);assert.equal(result.tracks.length,240);const easy=balancedDifficultyPool(result.tracks,'easy',()=>0.4);const medium=balancedDifficultyPool(result.tracks,'medium',()=>0.4);const shared=easy.filter(t=>medium.some(m=>m.id===t.id));assert.equal(shared.length,0,'easy and medium returned the same songs');assert(result.tracks.every(t=>t.cover===''),'a missing cover stays an empty string');assert.equal(searches,8)});
